= Microservice using Java, AWS Lambda, API Gateway and DynamoDB

This document explains how to use AWS API Gateway and AWS Lambda to create a simple microservice. The Lambda function uses Java runtime and the data is stored in DynamoDB.

Detailed steps are at http://docs.aws.amazon.com/lambda/latest/dg/with-on-demand-https-example-configure-event-source.html.

== AWS IAM Roles

IAM roles will have policies and trust relationships that will allow this role to be used in API Gateway and execute Lambda function.

. Create a new IAM role
+
```
aws iam create-role \
--role-name microserviceRole \
--assume-role-policy-document file://./trust.json
```
. Attach policy to the role
+
```
aws iam put-role-policy \
--role-name microserviceRole \
--policy-name microPolicy \
--policy-document file://./policy.json
```

More details: http://docs.aws.amazon.com/apigateway/latest/developerguide/setting-up.html

== Setup DynamoDB

. Create a DynamoDB table `Books`

== Lambda Functions

. Create a deployment package: `mvn -f books/pom.xml package`

=== Using Serverless Application Model (SAM)

This can also be deployed using AWS CLI as explained in link:readme-cli.adoc[].

. Create bucket: `aws s3 mb s3://books-microservice --region us-west-1`.
. Copy JAR file to S3 bucket: `aws s3 cp books/target/books-microservice-1.0-SNAPSHOT.jar s3://books-microservice/books-microservice-1.0-SNAPSHOT.jar`
. Deploy SAM
+
```
aws cloudformation deploy \
--template-file app-sam.yml \
--stack-name books-microservice \
--region us-west-1
```
+
. Test
.. Sample data for POST:
+
```
{
    "id": "1",
    "name": "test book",
    "isbn": "1234",
    "cost": "12.34"
}
```
+
. Delete SAM
+
```
aws cloudformation delete-stack \
--stack-name books-microservice \
--region us-west-1
```

== Local Maven Testing

. Invoke HTTP GET method using `mvn exec:java`



