= Couchbase Microservice HTTP Endpoint

This document explains how to use AWS API Gateway and AWS Lambda to create a simple microservice. The Lambda function uses Java and the data is stored in Couchbase running in EC2.

== IAM Roles

IAM roles will have policies and trust relationships that will allow this role to be used in API Gateway and execute Lambda function.

. Create a new IAM role: `aws iam create-role --role-name microRole --assume-role-policy-document file://./trust.json`
. Attach policy to the role: `aws iam put-role-policy --role-name microRole --policy-name microPolicy --policy-document file://./policy.json`

== Lambda Functions

. Create a deployment package: `mvn -f microservice-http-endpoint/pom.xml package`
. Create Lambda functions, one for each endpoint:
+
```
aws lambda create-function \
--function-name MicroserviceGetAll \
--role arn:aws:iam::598307997273:role/microRole \
--handler org.sample.serverless.aws.couchbase.BucketGetAll \
--zip-file fileb:///Users/arungupta/workspaces/serverless/aws/microservice/microservice-http-endpoint/target/microservice-http-endpoint-1.0-SNAPSHOT.jar \
--description "Microservice HTTP Endpoint - Get All" \
--runtime java8 \
--region us-west-1 \
--timeout 30 \
--memory-size 1024 \
--environment Variables={COUCHBASE_HOST=ec2-35-165-83-82.us-west-2.compute.amazonaws.com} \
--publish
```
+
```
aws lambda create-function \
--function-name MicroserviceGetOne \
--role arn:aws:iam::598307997273:role/microRole \
--handler org.sample.serverless.aws.couchbase.BucketGetOne \
--zip-file fileb:///Users/arungupta/workspaces/serverless/aws/microservice/microservice-http-endpoint/target/microservice-http-endpoint-1.0-SNAPSHOT.jar \
--description "Microservice HTTP Endpoint - Get One" \
--runtime java8 \
--region us-west-1 \
--timeout 30 \
--memory-size 1024 \
--environment Variables={COUCHBASE_HOST=ec2-35-165-83-82.us-west-2.compute.amazonaws.com} \
--publish
```
+
```
aws lambda create-function \
--function-name MicroservicePost \
--role arn:aws:iam::598307997273:role/microRole \
--handler org.sample.serverless.aws.couchbase.BucketPost \
--zip-file fileb:///Users/arungupta/workspaces/serverless/aws/microservice/microservice-http-endpoint/target/microservice-http-endpoint-1.0-SNAPSHOT.jar \
--description "Microservice HTTP Endpoint - Post" \
--runtime java8 \
--region us-west-1 \
--timeout 30 \
--memory-size 1024 \
--environment Variables={COUCHBASE_HOST=ec2-35-165-83-82.us-west-2.compute.amazonaws.com} \
--publish
```
+
. (OPTIONAL) Update the function:
+
```
mvn clean package;
aws lambda update-function-code \
--function-name <function-name> \
--zip-file fileb:///Users/arungupta/workspaces/serverless/aws/microservice/microservice-http-endpoint/target/microservice-http-endpoint-1.0-SNAPSHOT.jar \
--region us-west-2 \
--publish
```

== API Gateway Resources

. *Create API*
+
```
aws apigateway \
create-rest-api \
--name 'BookGET'
```
+
to see the output:
+
```
{
    "name": "BookGET", 
    "id": "xi5cgluxt7", 
    "createdDate": 1482949244
}
```
+
Value of `id` attribute is `api-id`.
+
*Find the root id*: `aws apigateway get-resources --rest-api-id xi5cgluxt7`. It shows the output:
+
```
{
    "items": [
        {
            "path": "/", 
            "id": "nobk6jl0x4"
        }
    ]
}
```
+
Value of `id` attribute is `root-id`. This is also the `parent-id` for top level resources.
+
. *Create resource*
+
```
aws apigateway create-resource \
--rest-api-id xi5cgluxt7 \
--parent-id nobk6jl0x4 \
--path-part books
```
+
to see the output:
+
```
{
    "path": "/books", 
    "pathPart": "books", 
    "id": "35um94", 
    "parentId": "nobk6jl0x4"
}
```
+
Value of `id` attribute is `resource-id`.
+
. *Create a `GET` method*
+
```
aws apigateway put-method \
--rest-api-id xi5cgluxt7 \
--resource-id 35um94 \
--http-method GET \
--authorization-type NONE
```
+
to see the response:
+
```
{
    "apiKeyRequired": false, 
    "httpMethod": "GET", 
    "authorizationType": "NONE"
}
```
+
. *Configure Lambda function*
.. Set Lambda function as destination of GET
+
```
aws apigateway put-integration \
--rest-api-id xi5cgluxt7 \
--resource-id 35um94 \
--http-method GET \
--type AWS \
--integration-http-method GET \
--uri arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:598307997273:function:MicroserviceGetAll/invocations
```
+
to see the output:
+
```
{
    "httpMethod": "GET", 
    "passthroughBehavior": "WHEN_NO_MATCH", 
    "cacheKeyParameters": [], 
    "type": "AWS", 
    "uri": "arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:598307997273:function:MicroserviceGetAll/invocations", 
    "cacheNamespace": "35um94"
}
```
+
.. Set `content-type` of GET method response
+
```
aws apigateway put-method-response \
--rest-api-id xi5cgluxt7 \
--resource-id 35um94 \
--http-method GET \
--status-code 200 \
--response-models "{\"application/json\": \"Empty\"}"
```
+
.. Set `content-type` of GET method integration response
+
```
aws apigateway put-integration-response \
--rest-api-id xi5cgluxt7 \
--resource-id 35um94 \
--http-method GET \
--status-code 200 \
--response-templates "{\"application/json\": \"Empty\"}"
```
+
. *Deploy the API*
+
```
aws apigateway create-deployment \
--rest-api-id xi5cgluxt7 \
--stage-name test
```
+
to see the output:
+
```
{
    "id": "b2yxli", 
    "createdDate": 1482951745
}
```
+
. *Grant permission* to allow API Gateway to invoke Lambda Function
+
```
aws lambda add-permission \
--function-name MicroserviceGetAll \
--statement-id apigateway-test-getall-1 \
--action lambda:InvokeFunction \
--principal apigateway.amazonaws.com \
--source-arn "arn:aws:execute-api:us-west-1:598307997273:xi5cgluxt7/*/GET/books"
```
+
to see the response
+
```
{
    "Statement": "{\"Sid\":\"apigateway-test-getall\",\"Resource\":\"arn:aws:lambda:us-west-1:598307997273:function:MicroserviceGetAll\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"apigateway.amazonaws.com\"},\"Action\":[\"lambda:InvokeFunction\"],\"Condition\":{\"ArnLike\":{\"AWS:SourceArn\":\"arn:aws:execute-api:us-west-1:598307997273:xi5cgluxt7/*/GET/*\"}}}"
}
```
+
Grant permission to the deployed API:
+
```
aws lambda add-permission \
--function-name MicroserviceGetAll \
--statement-id apigateway-test-getall-2 \
--action lambda:InvokeFunction \
--principal apigateway.amazonaws.com \
--source-arn "arn:aws:execute-api:us-west-1:598307997273:xi5cgluxt7/test/GET/books"
```
+
. *Test method*
+
```
aws apigateway test-invoke-method \
--rest-api-id xi5cgluxt7 \
--resource-id 35um94 \
--http-method GET
```


== TODO

. Generate Swagger endpoint for API

