= Couchbase Microservice HTTP Endpoint

This document explains how to use AWS API Gateway and AWS Lambda to create a simple microservice. The Lambda function uses Java and the data is stored in Couchbase running in EC2.

== Get ready for API Gateway

. Create a new IAM role: `aws iam create-role --role-name microRole --assume-role-policy-document file://./trust.json`
. Attach policy to the role: `aws iam put-role-policy --role-name microRole --policy-name microPolicy --policy-document file://./policy.json`

== Lambda Functions

. Create a deployment package: `mvn -f microservice-http-endpoint/pom.xml package`
. Create Lambda functions, one for each endpoint:
+
```
aws lambda create-function \
--function-name MicroserviceGetAll \
--role arn:aws:iam::598307997273:role/microRole \
--handler org.sample.serverless.aws.couchbase.BucketGetAll \
--zip-file fileb:///Users/arungupta/workspaces/serverless/aws/microservice/microservice-http-endpoint/target/microservice-http-endpoint-1.0-SNAPSHOT.jar \
--description "Microservice HTTP Endpoint - Get All" \
--runtime java8 \
--region us-west-1 \
--timeout 30 \
--memory-size 1024 \
--environment Variables={COUCHBASE_HOST=ec2-35-165-83-82.us-west-2.compute.amazonaws.com} \
--publish
```
+
```
aws lambda create-function \
--function-name MicroserviceGetOne \
--role arn:aws:iam::598307997273:role/microRole \
--handler org.sample.serverless.aws.couchbase.BucketGetOne \
--zip-file fileb:///Users/arungupta/workspaces/serverless/aws/microservice/microservice-http-endpoint/target/microservice-http-endpoint-1.0-SNAPSHOT.jar \
--description "Microservice HTTP Endpoint - Get One" \
--runtime java8 \
--region us-west-1 \
--timeout 30 \
--memory-size 1024 \
--environment Variables={COUCHBASE_HOST=ec2-35-165-83-82.us-west-2.compute.amazonaws.com} \
--publish
```
+
```
aws lambda create-function \
--function-name MicroservicePost \
--role arn:aws:iam::598307997273:role/microRole \
--handler org.sample.serverless.aws.couchbase.BucketPost \
--zip-file fileb:///Users/arungupta/workspaces/serverless/aws/microservice/microservice-http-endpoint/target/microservice-http-endpoint-1.0-SNAPSHOT.jar \
--description "Microservice HTTP Endpoint - Post" \
--runtime java8 \
--region us-west-1 \
--timeout 30 \
--memory-size 1024 \
--environment Variables={COUCHBASE_HOST=ec2-35-165-83-82.us-west-2.compute.amazonaws.com} \
--publish
```
+
. (OPTIONAL) Update the function:
+
```
mvn clean package;
aws lambda update-function-code \
--function-name <function-name> \
--zip-file fileb:///Users/arungupta/workspaces/serverless/aws/microservice/microservice-http-endpoint/target/microservice-http-endpoint-1.0-SNAPSHOT.jar \
--region us-west-2 \
--publish
```

== Create API Gateway resources

. *Create API*: `aws apigateway create-rest-api --name 'BookGET'` to see the output:
+
```
{
    "name": "BookGET", 
    "id": "xi5cgluxt7", 
    "createdDate": 1482949244
}
```
+
Note the value of `id` attribute. This is the `api-id`.
+
. *Find the parent id*: `aws apigateway get-resources --rest-api-id xi5cgluxt7`. It shows the output:
+
```
{
    "items": [
        {
            "path": "/", 
            "id": "nobk6jl0x4"
        }
    ]
}
```
+
Note the value of `id` attribute. This is the `parent-id`.
+
. *Create resource*: `aws apigateway create-resource --rest-api-id xi5cgluxt7 --parent-id nobk6jl0x4 --path-part books` to see the output:
+
```
{
    "path": "/books", 
    "pathPart": "books", 
    "id": "35um94", 
    "parentId": "nobk6jl0x4"
}
```
+
. *Create a `GET` method*: `aws apigateway put-method --rest-api-id xi5cgluxt7 --resource-id 35um94 --http-method GET --authorization-type NONE` to see the response:
+
```
{
    "apiKeyRequired": false, 
    "httpMethod": "GET", 
    "authorizationType": "NONE"
}
```
+
. *Configure Lambda function*
+
```
aws apigateway put-integration \
--rest-api-id xi5cgluxt7 \
--resource-id 35um94 \
--http-method GET \
--type AWS \
--integration-http-method GET \
--uri arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:598307997273:function:MicroserviceGetAll/invocations
```
+
to see the output:
+
```
{
    "httpMethod": "GET", 
    "passthroughBehavior": "WHEN_NO_MATCH", 
    "cacheKeyParameters": [], 
    "type": "AWS", 
    "uri": "arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:598307997273:function:MicroserviceGetAll/invocations", 
    "cacheNamespace": "35um94"
}
```


== TODO

. Generate Swagger endpoint for API

